doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
        types:
            conciertoId: App\Infrastructure\Persistence\Doctrine\Type\ConciertoIdType
            promotorId: App\Infrastructure\Persistence\Doctrine\Type\PromotorIdType
            recintoId: App\Infrastructure\Persistence\Doctrine\Type\RecintoIdType
            grupoId: App\Infrastructure\Persistence\Doctrine\Type\GrupoIdType
            medioPublicitarioId: App\Infrastructure\Persistence\Doctrine\Type\MedioPublicitarioIdType
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/src/Infrastructure/Persistence/Doctrine/Mapping'
                prefix: 'App\Domain'
                alias: App
